"""empty message

Revision ID: 0579c14970aa
Revises: None
Create Date: 2016-03-14 07:52:49.819810

"""

# revision identifiers, used by Alembic.
revision = '0579c14970aa'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_html',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('html', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('posting_body', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('img_urls', sa.String(), nullable=True),
    sa.Column('links', sa.String(), nullable=True),
    sa.Column('date_posted', sa.String(), nullable=True),
    sa.Column('posters_age', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parsed_html')
    ### end Alembic commands ###
